<a href="https://colab.research.google.com/github/Gm-shuvo/AI_Lab/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
file_path = '/content/drive/My Drive/hero/insurance_data.csv'
df = pd.read_csv(file_path)
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [ ]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#early_stop = EarlyStopping(monitor='accuracy', patience=50)

model.fit(X_train_scaled, y_train, epochs = 5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 9ms/step - loss: 0.5961 - accuracy: 0.6818
Epoch 1091/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5961 - accuracy: 0.6818
Epoch 1092/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5960 - accuracy: 0.6818
Epoch 1093/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5960 - accuracy: 0.6818
Epoch 1094/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5959 - accuracy: 0.6818
Epoch 1095/5000
1/1 [==============================] - 0s 15ms/step - loss: 0.5959 - accuracy: 0.6818
Epoch 1096/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5958 - accuracy: 0.6818
Epoch 1097/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5958 - accuracy: 0.6818
Epoch 1098/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5957 - accuracy: 0.6818
Epoch 1099/5000
1/1 [==============================]

In [ ]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 151ms/step - loss: 0.3550 - accuracy: 1.0000


[0.3549776077270508, 1.0]

In [ ]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 121ms/step


array([[0.7054848 ],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)

In [ ]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [ ]:
 coef, intercept = model.get_weights()
 coef, intercept
 ###This means W1, W2 and bais B

(array([[5.060863 ],
        [1.4086521]], dtype=float32), array([-2.913703], dtype=float32))

In [ ]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [ ]:
X_train_scaled['age']

0     0.22
13    0.29
6     0.55
17    0.58
24    0.50
19    0.18
25    0.54
16    0.25
20    0.21
3     0.52
7     0.60
1     0.25
5     0.56
27    0.46
8     0.62
18    0.19
12    0.27
23    0.45
22    0.40
15    0.55
26    0.23
4     0.46
Name: age, dtype: float64

In [ ]:
def prediction_function(age, affordibility):
  weight_sum = coef[0] * age + coef[1] * affordibility + intercept
  return sigmoid(weight_sum)

 
prediction_function(.47, 1) #output same as above predictions

0.705484819775958

In [ ]:
prediction_function(.18, 1)

0.35569571637887243

In [ ]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [ ]:
def log_loss(y_true, y_prediction):
  epsilon = 1e-15
  y_prediction_new = [max(i, epsilon) for i in y_prediction]
  y_prediction_new = [min(i, 1 - epsilon) for i in y_prediction]
  y_prediction_new = np.array(y_prediction_new)
  return -np.mean(y_true* np.log(y_prediction_new) + (1 - y_true)* np.log(1 - y_prediction_new))



In [ ]:
def gradient_descent(age, affordibility, y_true, epchos, loss_thresold):
  w1 = w2 = 1
  bias = 0
  learning_rate = 0.5
  
  # print(y_prediction)
  age = age.astype('float32')
  affordibility = affordibility.astype('float32')
  n = len(age)
  for i in range(epchos):
    weight_sum = w1 * age + w2 * affordibility + bias
    y_prediction = sigmoid_numpy(weight_sum)
    loss = log_loss(y_true, y_prediction)
    # print(y_prediction)
    w1d = (1/ n) * np.dot(np.transpose(age), ( y_prediction - y_true))
    w2d = (1 / n) * np.dot(np.transpose(affordibility), (y_prediction - y_true))
    bias_d = np.mean(y_prediction - y_true)

    w1 = w1 - learning_rate * w1d
    w2 = w2 - learning_rate * w2d
    bias = bias - learning_rate * bias_d

    print(f'Epoch: {i}, w1: {w1}, w2: {w2}, bias:{bias}, loss:{loss}')
    if loss <= loss_thresold:
      break
  return w1, w2, bias




In [ ]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000, 0.46)


Epoch: 0, w1: 0.9749076312444013, w2: 0.9483481212095781, bias:-0.11341868205503984, loss:0.7113403040521091
Epoch: 1, w1: 0.9556229720153815, w2: 0.9058873666958376, bias:-0.21223491294817493, loss:0.6812647562339783
Epoch: 2, w1: 0.9416488477557515, w2: 0.8719790808179162, bias:-0.29775789854201407, loss:0.6591474300534474
Epoch: 3, w1: 0.9323916971485311, w2: 0.8457541465759277, bias:-0.3715094781734727, loss:0.643152337486246
Epoch: 4, w1: 0.9272267446961745, w2: 0.8262362845919349, bias:-0.435066435824741, loss:0.6316872839327551
Epoch: 5, w1: 0.9255469368115804, w2: 0.812440274791284, bias:-0.4899449077519504, loss:0.6234717152324135
Epoch: 6, w1: 0.9267936105280626, w2: 0.8034374998374418, bias:-0.5375299562107433, loss:0.6175321092715204
Epoch: 7, w1: 0.9304717014552388, w2: 0.7983919951048764, bias:-0.5790424346923828, loss:0.613159187807207
Epoch: 8, w1: 0.9361540780053144, w2: 0.7965748770670457, bias:-0.6155315116047859, loss:0.6098518145761975
Epoch: 9, w1: 0.9434791212954

(5.204865117165474, 1.4622656255960471, -3.027050470763987)

In [ ]:
coef, intercept 

(array([[5.060863 ],
        [1.4086521]], dtype=float32), array([-2.913703], dtype=float32))

In [97]:
#define MyCustomModel
class MyNN():
  def __int__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0
  

  def fit(self, X, y, epchos, loss_thresold):
    self.w1,self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'], y, epchos, loss_thresold)

  def predict(self, x_test):
    weight_sum = self.w1 * x_test['age'] + self.w2 * x_test['affordibility'] + self.bias
    return sigmoid_numpy(weight_sum)


  def gradient_descent(self, age, affordibility, y_true, epchos, loss_thresold):
    w1 = w2 = 1
    bias = 0
    learning_rate = 0.5
    
    # print(y_prediction)
    age = age.astype('float32')
    affordibility = affordibility.astype('float32')
    n = len(age)
    for i in range(epchos):
      weight_sum = w1 * age + w2 * affordibility + bias
      y_prediction = sigmoid_numpy(weight_sum)
      loss = log_loss(y_true, y_prediction)
      # print(y_prediction)
      w1d = (1/ n) * np.dot(np.transpose(age), ( y_prediction - y_true))
      w2d = (1 / n) * np.dot(np.transpose(affordibility), (y_prediction - y_true))
      bias_d = np.mean(y_prediction - y_true)

      w1 = w1 - learning_rate * w1d
      w2 = w2 - learning_rate * w2d
      bias = bias - learning_rate * bias_d
      if i%50 == 0:
        print(f'Epoch: {i}, w1: {w1}, w2: {w2}, bias:{bias}, loss:{loss}')
      if loss <= loss_thresold:
        break
    return w1, w2, bias


In [98]:
myModel = MyNN()
myModel.fit(X_train_scaled, y_train, 8000, 0.4631)

Epoch: 0, w1: 0.9749076312444013, w2: 0.9483481212095781, bias:-0.11341868205503984, loss:0.7113403040521091
Epoch: 50, w1: 1.5033195667643744, w2: 1.1083847853270445, bias:-1.231904749165882, loss:0.5675865275324093
Epoch: 100, w1: 2.2007131539313205, w2: 1.2941583882678642, bias:-1.660700938918374, loss:0.53906804363209
Epoch: 150, w1: 2.849572799898598, w2: 1.3696895458481528, bias:-1.9861058850180022, loss:0.5176462124781493
Epoch: 200, w1: 3.44301700596434, w2: 1.4042218855836177, bias:-2.2571370141072706, loss:0.5005011056117021
Epoch: 250, w1: 3.982450526151501, w2: 1.4239127324386078, bias:-2.494377409192648, loss:0.48654089005126716
Epoch: 300, w1: 4.472179559027178, w2: 1.4387879859317434, bias:-2.7073878473178894, loss:0.47508147071750134
Epoch: 350, w1: 4.91724590371799, w2: 1.452566060152921, bias:-2.9011763916774234, loss:0.46561474779721085


In [100]:
#MyModel prediction
myModel.predict(X_test_scaled) 

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64

In [102]:
#keras model prediction
model.predict(X_test_scaled)

1/1 [==============================] - 0s 25ms/step


array([[0.7054848 ],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)